# fly.toml app configuration file generated for movies-database-manager on 2024-02-13T19:11:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'movies-database-manager'
primary_region = 'mad'

[build]
  build = "npm run build"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
